### ISSUE TITLE
I got an error quit from last commit

### ISSUE THREAD

**Issue by GTrunSec** [thomasjm/julia2nix#10]
output as following:
```
 ~/julia2nix/julia2nix
Cloning https://github.com/JuliaRegistries/General.git to /run/user/1000/tmpknigzdic/registry
Got registry revision fb98abf1e93c87eac2df08beb38a48db19b9ab05
Got registry sha256 00z4ybrlrb6mvbl73p23fs6468c7q6l8jw1hax83arip70c7i4fv
Traceback (most recent call last):
  File "/home/gtrun/julia2nix/gather_packages.py", line 125, in <module>
    main()
  File "/home/gtrun/julia2nix/gather_packages.py", line 109, in main
    formatted_dicts = p.map(process_item, manifest.keys())
  File "/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.process_item'
Traceback (most recent call last):
  File "/home/gtrun/julia2nix/julia2nix", line 45, in <module>
    main()
  File "/home/gtrun/julia2nix/julia2nix", line 40, in main
    packages_nix = subprocess.check_output([script_dir.joinpath("gather_packages.py"), environment_dir, repo_url, str(workers)]).decode()
  File "/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/yi9a1fafijn0nf5m8qkmnl955vi2mncm-python3-3.8.6/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '[PosixPath('/home/gtrun/julia2nix/gather_packages.py'), PosixPath('.'), 'https://github.com/JuliaRegistries/General.git', '8']' returned non-zero exit status 1.
```
but the rev of 3beb21030e59881c93ea5589b716eef11cefe360 works on me.

**Comment by thomasjm** [comment]
Thanks for the report. Looks like making `multiprocessing` happy is more tricky than I thought. I've reverted the offending commit for now.
