### ISSUE TITLE
cloning git tree

### ISSUE THREAD

**Issue by jtrakk** [thomasjm/julia2nix#4]
julia2nix tries to check out a git tree instead of a commit, so it errors:

```
% ../julia2nix/julia2nix 
Cloning https://github.com/JuliaRegistries/General.git to /run/user/1000/tmpeti41tl7/registry
Got registry revision 89ae08aab842ed801073c173601c15bf7ad436b9
Got registry sha256 1fgn2ji6dbch62wkvq4zaji2cxi9yhjzvrg833nhpjp6vwvrdrb2
Initialized empty Git repository in /run/user/1000/git-checkout-tmp-TiI16d73/Pipe.jl-6842804/.git/
From https://github.com/oxinabox/Pipe.jl
 * [new branch]      master         -> origin/master
 * [new branch]      nocompatneeded -> origin/nocompatneeded
 * [new branch]      ox/require     -> origin/ox/require
 * [new branch]      ox/seven       -> origin/ox/seven
 * [new branch]      release        -> origin/release
 * [new tag]         v0.0.1         -> v0.0.1
 * [new tag]         v0.0.2         -> v0.0.2
 * [new tag]         v0.0.3         -> v0.0.3
 * [new tag]         v1.0.0         -> v1.0.0
 * [new tag]         v1.1.0         -> v1.1.0
 * [new tag]         v1.2.0         -> v1.2.0
 * [new tag]         v1.3.0         -> v1.3.0
fatal: Cannot switch branch to a non-commit '6842804e7867b115ca9de748a0cf6b364523c16d'
Unable to checkout 6842804e7867b115ca9de748a0cf6b364523c16d from https://github.com/oxinabox/Pipe.jl.git.
Traceback (most recent call last):
  File "/home/user/projects/julia2nix/gather_packages.py", line 78, in <module>
    sha256 = fetch_sha256(url, rev=githash)
  File "/home/user/projects/julia2nix/nix_util.py", line 12, in fetch_sha256
    p = subprocess.run([
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-prefetch-git', '--url', 'https://github.com/oxinabox/Pipe.jl.git', '--rev', '6842804e7867b115ca9de748a0cf6b364523c16d', '--quiet']' returned non-zero exit status 1.
```

**Comment by thomasjm** [comment]
Sorry @jtrakk , the Python script wasn't using the specially patched `nix-prefetch-git` from this package. Can you try the latest commit I just pushed?

**Comment by jtrakk** [comment]
Yep that works. Thanks.
